config/routes.rb
Subloom::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  match '/users/:id/following', :to => 'users#following', via: 'get', as: 'following_users'
  match '/users/:id/followers', :to => 'users#followers', via: 'get', as: 'followers_users'
  root :to => "pages#index"

  resources :links
  resources :votes, only: [:create, :destroy]
  resources :profiles
  resources :follow_relationships, only: [:create, :destroy]
  resources :save_relationships, only: [:create, :destroy]
  get '/photographer/:id' => 'profiles#show_photog', as: 'photographer'
  get '/photographers/' => 'users#photogs_index', as: "photogs_index"

  get 'search' => 'search#index'

  match '/about', to: 'pages#about', via:'get'
  match '/contact', to: 'pages#contact', via:'get'

  

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		@links = Link.basic_search(:title => params[:q]).paginate(page: params[:page], :per_page => 5)
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_searchform.html.erb
<%= form_tag(search_url, :method => "get") do %>
	<%= text_field_tag(:q, nil, :placeholder => "Search") %>
	<%= submit_tag("Search", class: "btn btn-default") %>
<% end %>

app/views/search/index.html.erb
<div class="row-fluid">

 <!-- data-spy="affix" data-offset-top="000"  -->
<div class="span1 offset1" id="sidebar">
    <%= link_to "Back to home", root_url, class:"btn btn-primary" %>
    <br><br>
    <% if can? :create, Link %>
        <%= link_to "Add a link", new_link_path, class:"btn btn-primary"%> <br/>
    <% end %>
</div>

<div class="span8">

<%= render 'links/showlinks', :links => @links %>

</div>

</div>