config/routes.rb
Subloom::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  match '/users/:id/following', :to => 'users#following', via: 'get', as: 'following_users'
  match '/users/:id/followers', :to => 'users#followers', via: 'get', as: 'followers_users'
  root :to => "pages#index"

  resources :links
  resources :votes, only: [:create, :destroy]
  resources :profiles
  resources :follow_relationships, only: [:create, :destroy]
  resources :save_relationships, only: [:create, :destroy]
  get '/photographer/:id' => 'profiles#show_photog', as: 'photographer'
  get '/photographers/' => 'users#photogs_index', as: "photogs_index"

  get 'search' => 'search#index'

  match '/about', to: 'pages#about', via:'get'
  match '/contact', to: 'pages#contact', via:'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :votes
  has_one :profile, :dependent => :destroy
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",       :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      :url => "/system/:attachment/:id/:style/:filename"

  has_many :follow_relationships, foreign_key: "follower_id", :dependent => :destroy
  has_many :followed_users, through: :follow_relationships, source: :followed
  
  has_many :reverse_follow_relationships, foreign_key: "followed_id", class_name: "FollowRelationship", dependent: :destroy
  has_many :followers, through: :reverse_follow_relationships, source: :follower

  has_many :save_relationships, foreign_key: "user_id", :dependent => :destroy
  has_many :saved_links, through: :save_relationships, source: :link

  after_create :create_profile

  ROLES = %w[photog user]

  def following?(other_user)
    follow_relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    follow_relationships.create(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    follow_relationships.find_by(followed_id: other_user.id).destroy!
  end

  def save_link!(link)
    save_relationships.create(link_id: link.id)
  end

  def unsave_link!(link)
    save_relationships.find_by(link_id: link.id).destroy!
  end

  def saved_link?(link)
    save_relationships.find_by(link_id: link.id)
  end

 	def create_profile
 		# debugger
  		profile = Profile.create(:user_id => self.id)
  	end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	end
	
	def photogs_index
		@users = User.where(:role => "photog").paginate(page: params[:page], :per_page => 20)
		@title = "Photographer Directory"
	end

	def following
		@title = "Following"
		@user = User.find(params[:id])
		@users = @user.followed_users.paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@user = User.find(params[:id])
		@users = @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end

end

app/views/users/_follow.html.erb
<%= form_tag({:controller => :follow_relationships, :action => :create}, remote:true) do |f| %>
	<%= hidden_field_tag :followed_id, @user.id %>
	<%= submit_tag "Follow", class:"btn btn-large btn-primary" %>
<% end %>

app/views/users/_followform.html.erb
<div id="follow_form">
	<% if !current_user %>
		<%= render 'users/follow' %>
	<% elsif current_user != @user %>
		<% if !current_user.following?(@user) %>
			<%= render 'users/follow' %>
		<% else %>
			<%= render 'users/unfollow' %>
			<% end %>
	<% end %>	
</div>

app/views/users/_followstats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_users_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_users_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.follow_relationships.find_by(followed_id: @user.id), html: {method: :delete}, remote: true) do |f| %>

	<%= f.hidden_field :followed_id %>
	<%= f.submit "Unfollow", class:"btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.email, user.profile %>
</li>

app/views/users/photogs_index.html.erb
<div class="container">
<% provide(:title, @title) %>
<div class="row">
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="unstyled">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>