config/routes.rb
Subloom::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  match '/users/:id/following', :to => 'users#following', via: 'get', as: 'following_users'
  match '/users/:id/followers', :to => 'users#followers', via: 'get', as: 'followers_users'
  root :to => "pages#index"

  resources :links
  resources :votes, only: [:create, :destroy]
  resources :profiles
  resources :follow_relationships, only: [:create, :destroy]
  resources :save_relationships, only: [:create, :destroy]
  get '/photographer/:id' => 'profiles#show_photog', as: 'photographer'
  get '/photographers/' => 'users#photogs_index', as: "photogs_index"

  get 'search' => 'search#index'

  match '/about', to: 'pages#about', via:'get'
  match '/contact', to: 'pages#contact', via:'get'

  

end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
	has_many :votes
	validates :user_id, presence: true
	has_many :save_relationships, foreign_key: "link_id", dependent: :destroy
	has_many :users_who_saved, through: :save_relationships, source: :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "profile_default.png", :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
		:url => "/system/:attachment/:id/:style/:filename"
	
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_filter :authenticate_user!, :only =>[:new, :create, :destroy]
	load_and_authorize_resource
	
	def index
	end

	def show
		@link = Link.find(params[:id])
	end

	def new
		@link = Link.new
	end

	def create
		@link = current_user.links.new(link_params)
		if @link.save
			flash[:notice] = "Link submitted!"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def destroy
		# debugger
		@link = Link.find(params[:id])
		if @link.destroy
			flash[:notice] = "Post deleted!"
			redirect_to profile_path(current_user.profile)
		else
			flash[:alert] = "Post deletion failed."
			redirect_to profile_path(current_user.profile)
		end
	end
	

	private
		def link_params
			params.require(:link).permit!
		end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_save.html.erb
<%= form_tag( { :controller => :save_relationships, :action => :create }, remote:true) do |f| %>
	<%=  hidden_field_tag :link_id, link.id %>
	<%= submit_tag "Save", class: "btn" %>
<% end %>

app/views/links/_saveform.html.erb
<div id="save_form_<%= link.id %>">
<% if !current_user || !current_user.saved_link?(link) %>
	<%= render '/links/save', :link => link %>
<% else %>
	<%= render '/links/unsave', :link => link %>
<% end %>
</div>

app/views/links/_showlinks.html.erb
<ul class= "thumbnails">
  <% links.each do |link| %>
    <li class="span3">
    <div class="row-fluid">
        <div class="span6">
            <p class="thumbnail_heading">
                <strong class="thumbnail_title"><%= link.title %> </strong>
            </p>
        </div>
        <div class="span4">
            <%= render 'links/saveform', :link => link %>
        </div>
        <div class="span1">
            <span id="vote_count_<%= link.id %>">
                <strong><%= link.votes.count %></strong>
            </span>
        </div>
        <div class="span1">
                <span id= "upvote_<%= link.id %>">
                    <% if current_user && current_user.votes.where(:link_id => link.id).present? %>
                    
                        <!-- <%= link_to "-", vote_path(:id => current_user.id, :vote => {:link_id => link.id, :user_id => current_user.id}), :method => :delete, remote: true %> -->
                    <% else %>
                        <%= link_to "<i class='icon-arrow-up'></i>".html_safe, votes_path(:vote => {:link_id => link.id}), :method => :post, remote: true %>
                    <% end %>
                </span>
        </div>
    </div>

    <div class="thumbnail_image">
        <%= link_to image_tag(link.image.url),  link_path(link)%>
    </div>

            <!-- <a href=<%=link.url%>> <%= link.url%></a> -->
            By:
            <% if link.user %>
            <%= link_to link.user.email, profile_path(link.user.profile) %>
            <% end %>
    
    </li>
  <% end %>
</ul>
    <%= will_paginate @links %>

app/views/links/_unsave.erb
<%= form_for(current_user.save_relationships.find_by(link_id: link.id), remote:true, html: {method: :delete} ) do |f| %>
	<%= f.submit "Unsave", class: "btn" %>
<% end %>

app/views/links/new.html.erb
<div class="container">

    <%= form_for(@link) do |f| %>
    <% if @link.errors.any? %>
    <div id="error_explanation">
        <!-- <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2> -->
        <ul>
            <% @link.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :url %><br />
        <%= f.text_field :url %>
    </div>

    <div class="image">
        <%= f.label "Image: " %>
        <%= f.file_field :image %>
    </div>

    <br>

    <div class="actions">
        <%= f.submit %>
    </div>

    <% end %>

</div>

app/views/links/show.html.erb
<div class="container">
<%= @link.title %> <br>
<%= @link.url %><br>
<%= image_tag @link.image.url %>
</div>