config/routes.rb
Subloom::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  match '/users/:id/following', :to => 'users#following', via: 'get', as: 'following_users'
  match '/users/:id/followers', :to => 'users#followers', via: 'get', as: 'followers_users'
  root :to => "pages#index"

  resources :links
  resources :votes, only: [:create, :destroy]
  resources :profiles
  resources :follow_relationships, only: [:create, :destroy]
  resources :save_relationships, only: [:create, :destroy]
  get '/photographer/:id' => 'profiles#show_photog', as: 'photographer'
  get '/photographers/' => 'users#photogs_index', as: "photogs_index"

  get 'search' => 'search#index'

  match '/about', to: 'pages#about', via:'get'
  match '/contact', to: 'pages#contact', via:'get'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default navbar-custom ">
    <!-- <div class="navbar-inner"> -->
        <div class="container-fluid">

            <div class="navbar-header">
                <%= link_to "Subloom", root_url, id: "logo", class: "navbar-brand"%>
            </div>
            <nav>
            <ul class="nav navbar-nav">
                <li class= "nav navbar-form">
                    <%= render 'search/searchform' %>
                </li>
            </ul>
            <ul class="nav pull-right">
                <li><%= link_to "Home",   root_url %></li>
                <li><%= link_to "Photographers", photogs_index_path %></li>
                <%# If user is logged in, show log out link %>
                <% if current_user.present? %>
                <li><%= link_to 'Profile', profile_path(current_user.profile) %></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
                <%# If user is not logged in, show signup and login links %>
                <% else %>

                <li><%= link_to 'Sign In', new_user_session_path %></li>
                <li><%= link_to 'Register Now!', new_user_registration_path %> </li>
                <% end %>
            </ul>
        </nav>
    </div>
<!-- </div> -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		<%= full_title(yield(:title)) %>
	</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
		<% [:notice, :error, :alert].each do |level| %>
		<% unless flash[level].blank? %>
		<div data-alert="alert" class="alert alert-<%= level %> fade in">
			<a class="close" data-dismis="alert" href="#">&times;</a>
			<%= content_tag :p, flash[level] %>
		</div>
		<% end %>
		<% end %>

		<%= yield %>

		<%= render 'layouts/footer' %>
	</div>
</body>
</html>